version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    parallelism: 3
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            set -e
            #echo "TestCartController" > class.txt
            #echo "TestMenuController" >> class.txt
            #echo "TestImageController" >> class.txt
            TEST_FILES=$(circleci tests split --split-by=timings --timings-type=classname TestCartController)
            mkdir -p test-results
            pytest openapi_server/test/test_cart_controller.py::TestCartController --verbose --junitxml=test-results/junit.xml $TEST_FILES
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  sample:
    jobs:
      - build-and-test
