version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    parallelism: 3
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            set -e
            echo openapi_server.test.test_menu_controller.TestMenuController > TestCartController.tst
            echo openapi_server.test.test_menu_controller.TestImageController > TestImageController.tst
            echo openapi_server.test.test_menu_controller.TestOuiOuiController > TestOuiOuiController.tst
            TEST_FILES=$(circleci tests glob "Test_*.tst" | circleci tests split --split-by=timings --timings-type=classname)
            mkdir -p test-results
            pytest --verbose --junitxml=test-results/junit.xml $TEST_FILES
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  sample:
    jobs:
      - build-and-test
