version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    parallelism: 3
    # machine:
    #   image: ubuntu-2004:2023.07.1
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            #set -e
            mkdir -p test-results
            TEST_FILES=$(circleci tests glob "openapi_server/**/test_*.py" | circleci tests split --split-by=timings)
            #TEST_FILES="$PWD/"$(circleci tests glob "openapi_server/**/test_*.py")
            echo $TEST_FILES
            #echo $TEST_FILES | circleci tests run --command="xargs pytest -o junit_family=legacy --junitxml=test-results/junit.xml" --verbose --split-by=timings --timings-type=file
            pytest --verbose --junitxml=test-results/junit.xml $TEST_FILES


      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  sample:
    jobs:
      - build-and-test
