version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    parallelism: 3
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            set -e
            #touch class.txt
            echo "openapi_server.test.test_cart_controller.TestCartController" > class.txt
            echo "openapi_server.test.test_image_controller.TestImageController" >> class.txt
            echo "openapi_server.test.test_menu_controller.TestMenuController" >> class.txt
            
            TEST_FILES=$(circleci tests glob "openapi.*" | circleci tests split --split-by=timings --timings-type=classname)
            
            #TEST_FILES=$(circleci tests split --split-by=timings --timings-type=classname class.txt)
            echo $TEST_FILES
            TESTFILES=$(echo $TEST_FILES | tr "." "/" | sed 's/\(.*\)\//\1.py::/')
            echo $TESTFILES
            mkdir -p test-results
            #pytest --verbose --junitxml=test-results/junit.xml $TESTFILES
            
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  sample:
    jobs:
      - build-and-test

# version: 2.1

# orbs:
#   python: circleci/python@1.2

# jobs:
#   build-and-test:
#     parallelism: 2
#     docker:
#       - image: cimg/python:3.8
#     steps:
#       - checkout
#       - python/install-packages:
#           pkg-manager: pip
#       - run:
#           name: Run tests
#           command: |
#             set -e
#             TEST_FILES=$(circleci tests glob "openapi_server/**/test_*.py" | circleci tests split --split-by=timings)
#             mkdir -p test-results
#             pytest --verbose --junitxml=test-results/junit.xml $TEST_FILES
#       - store_test_results:
#           path: test-results
#       - store_artifacts:
#           path: test-results
# workflows:
#   sample:
#     jobs:
#       - build-and-test
